### ISSUE TITLE
A cropped picture returns to its initial size when we save it

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/pix#100]
```
 * Pix version 2.4.6
 * Distribution - Mint 19.3 and 20
```

**Issue**

When saving a cropped picture, the picture returns to its initial size.

**Steps to reproduce**

Open a PNG picture.
Crop the picture.
Save it with CTRL-S or with File - Save
-> The picture is saved but the cropping is canceled, the size returns to the initial size at screen and in the saved file.

**Expected behaviour**

The picture should remain cropped.

**Other information**

This bug is aleatory.

**Comment by icarter09** [comment]
Pix v2.4.8
Mint 20

Cropping the picture and using the `File->Save` or CTRL-S` will result in the steps provided. Using the `Save` option in the menu provided when altering an image will maintain the cropped image.

![save pix crop](https://user-images.githubusercontent.com/4397312/89248054-bb4b0a00-d5dc-11ea-8d45-112322c2de5b.gif)

**Comment by InfoLibre** [comment]
Why did you close this bugrepor ??? This bug will not be fixed ?

**Comment by icarter09** [comment]
I closed it because there is a work around for the issue. I can reopen if you want, but since there is a current work around, it is lower on priority.

**Comment by InfoLibre** [comment]
As I don't take time to make bugreports to have a workaround but to help improve free software beeing better, I would prefer you reopen this bugreport, please.

**Comment by InfoLibre** [comment]
Incredible. I just had this problem again, after using Pix without any bug since weeks.
I was cropping a picture and saving with CTRL-S. When I press CTRL-S, the cropped picture returns to its initial size.

**Comment by icarter09** [comment]
@InfoLibre I tried several times to duplicate this issue, but looks to still be working correctly for me.

**Comment by InfoLibre** [comment]
It's random and with this 2.4.11 version, it rarely happens. This has happened twice since I installed Linux Mint 20 Cinnamon.

**Comment by InfoLibre** [comment]
It didn't happen for a while.
