### ISSUE TITLE
bug: Pix hangs when a mounted Samba share in Caja becomes inaccessible.

### ISSUE THREAD

**Issue by mr-blobbyyy** [linuxmint/pix#11]
Samba client 2:4.3.11+dfsg-0ubuntu0.16.04.3
LM 18.1 mate release
Pix 1.2.1
Caja 1.16.1

hangs = app loads very slowly with no other thumbnails loaded. Still able to exit the app.
inaccessible = gufw blocking target address, Samba server shuts down, ethernet unplugged, etc.
Issue is solved by un-mounting the inaccessible share via the "eject" icon next to the share name in Caja.

**Comment by ICHx** [comment]
I can see the same problem with gvfs.
I used nautilus 3.22.3 to connect a webdav server.  When I open a file with GIMP, things may(still have a probability to fail) work fine.  However, for Pix, it would never open any file, the interface would become like this.
![2017-04-02 18-30-18](https://cloud.githubusercontent.com/assets/11556527/24586399/7ed05eb0-1765-11e7-8f93-19a087933c06.png)

**Comment by icarter09** [comment]
@mr-blobbyyy and @ICHx: any update on this issue?

**Comment by ICHx** [comment]
I don't have the installation anymore

**Comment by icarter09** [comment]
@ICHx no worries and thanks for the update.

**Comment by catscarlet** [comment]
Hello.

I'm still encountering this (or similar) bug, a lot times. **Pix freezes a short time if there is an inaccessible mount-point**

Linux Mint 20.3
Pix 2.8.4
Frequency: Always.


Step:
1. Mount an accessible filesystem through a remote samba-service.
2. Make that samba-service inaccessible (like, shutdown that samba-server, unplug the samba-server, etc.)
3. Open Pix. (no matter whether open a local image or open Pix in console)


Pix freezes a short time (with some WARNING if Pix is opened in console), then Pix opens as usual.


![screenshot_on_b85m_by_flameshot_at_2024-03-29_23-52-03](https://github.com/linuxmint/pix/assets/10594035/dcf40326-1a7e-4df3-a20e-91c5aa93221d)


If I umount the inaccessible mount-point, pix restores.

Here is the log (as the same in screenshot)

```
cat@cat-B85M-D3H:~$ pix 

(pix:398745): GLib-GObject-WARNING **: 23:27:51.963: g_type_class_add_private() called multiple times for the same type

(pix:398745): GLib-GIO-CRITICAL **: 23:27:55.171: g_file_info_set_icon: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:27:55.171: g_file_info_set_display_name: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GObject-CRITICAL **: 23:27:55.171: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:27:58.243: g_file_info_set_icon: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:27:58.243: g_file_info_set_display_name: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GObject-CRITICAL **: 23:27:58.243: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:28:01.315: g_file_info_set_icon: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:28:01.315: g_file_info_set_display_name: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GObject-CRITICAL **: 23:28:01.315: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:28:07.459: g_file_info_set_icon: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GIO-CRITICAL **: 23:28:07.459: g_file_info_set_display_name: assertion 'G_IS_FILE_INFO (info)' failed

(pix:398745): GLib-GObject-CRITICAL **: 23:28:07.459: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
cat@cat-B85M-D3H:~$ 

```
