### ISSUE TITLE
gdk_wayland_display_get_type

### ISSUE THREAD

**Issue by Freeman310** [linuxmint/pix#114]
```
 * Pix version (pix --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
OpenSUSE Tumbleweed
**Issue**

When I run the application on the OpenSUSE TUMBLEWEED distribution, I get an error:
<remmina: symbol lookup error: remmina: undefined symbol: gdk_wayland_display_get_type>

**Comment by leigh123linux** [comment]
remmina has the undefined symbol not pix.

**Comment by Freeman310** [comment]
small mistake. i am experiencing the same problem in remmina too. but I get the same error when running pix. only instead of remmina the inscription pix

**Comment by leigh123linux** [comment]
File the issue at Suse, their package is stale.

https://build.opensuse.org/package/show/openSUSE:Factory/pix

It looks like something has changed in gtk3.

**Comment by Freeman310** [comment]
After I installed pix from another repository, there were no positive changes. I am still getting this error: pix: symbol lookup error: /usr/lib64/libclutter-gtk-1.0.so.0: undefined symbol: gdk_wayland_display_get_type
