### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by 2beta** [linuxmint/pix#12]
On Pix 1.2.1 the anti-aliasing is really bad. The same image on gThumb (3.4.3) has no problem.

On Left : Pix
On Right : gThumb

Specialy on hair and sweatshirt
![capture du 2016-12-27 16-43-16](https://cloud.githubusercontent.com/assets/3958206/21502942/d6f6ef4e-cc53-11e6-8d88-b1388e27bf3e.png)

I'm not the only one with this issue
https://darktable-fr.tuxfamily.org/forums/sujet/probleme-image-exportee/#post-4407

**Comment by phavel** [comment]
It is really problem.

**Comment by gordon-morehouse** [comment]
The linked thread is gone, but looking at the URL it looks like they were talking about image export.

This is also a problem when viewing images in the viewer (e.g. double-click a thumb, etc). Scaling up *and* down produces results that look absolutely horrible. :(

It might be as simple as switching to bicubic or lanczos for the default scaling algorithm, assuming an external library is in use.

**Comment by phavel** [comment]
Please correct it…

**Comment by aritorhamo** [comment]
Just giving a notice that jpeg images still don't look good in Pix version 2.2.1. At least on my system (Linux Mint 19.2) they look blurred compared to Xviewer. I'd say the difference is larger than subtle.

**Comment by samzorn** [comment]
is there no antialiasing option in version 2.8.4 ??

**Comment by clefebvre** [comment]
Pix is now rebased on gthumb 3.12 so I'm closing this.
