### ISSUE TITLE
Unable to play video

### ISSUE THREAD

**Issue by burntex** [linuxmint/pix#126]
```
 Pix version 2.4.6 Mint 19.3
```
For some reason Pix has stopped playing videos. Can hear the audio but no video. gThumb is also showing same problem. uninstalled and reinstalled - no change. No log msgs that I can see - syslog or terminal.

VLC and xPlayer work fine.

Any suggestions?

**Comment by burntex** [comment]
OK a little progress. I installed gstreamere1.0-gtk3 and gThumb now works with video but not Pix. running Pix with --gst-debug-level=2 i get the following error

vaapi gstvaapiutils.c:77:gst_vaapi_warning: va_getDriverName() failed with unknown libva error,driver_name=(null)
 WARN                   vaapi gstvaapiutils.c:77:gst_vaapi_warning: va_getDriverName() failed with unknown libva error,driver_name=(null)
 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<capsfilter10> warning: not negotiated
 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<capsfilter10> warning: not negotiated
 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<capsfilter12> warning: not negotiated
 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<capsfilter12> warning: not negotiated
 WARN                   pulse pulsesink.c:702:gst_pulsering_stream_underflow_cb:<pulsesink0> Got underflow

vainfo gives
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

I have 2 monitors one is on the nvidia card and the other is on the integrated Intel 630.

doing a 
apt install libva2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libva2 is already the newest version (2.1.0-3).
The following packages were automatically installed and are no longer required:
  gir1.2-mate-desktop gir1.2-mate-panel grilo-plugins-0.3-base libgom-1.0-0 libhal1-flash liblua5.3-0 libmediaart-2.0-0 libtotem0 libunshield0 libxfconf-0-2 totem-common unshield
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 169 not upgraded.

I recall I did some autoremoves a few weeks ago. Suspect i removed something.

I may remove libva2 and reinstall and see what happens.

**Comment by icarter09** [comment]
@burntex is this happening with every video? I'm not seeing any issues, but also running Pix 2.6.3 and Mint 20 64bit.

**Comment by burntex** [comment]
I had some issues with my Nvidia driver not having installed the vdpau pkg. I have learned a lot the last couple of days about the video system.. things are working pretty good now. I still have a minor issue with .mkv (h.265) files created with Handbrake and intel qsv not always syncing properly when I play them on the intel i965_drv_video.so. But I think that is a gstreamer issue as it happens on other players too.
Thanks for the response .. I will post back on the forum indicating my progress.. just been busy trying to figure this stuff out.
I like to us PIX to screen capture images of our Vacation videos..also like the photo enhancing capabilities .. easy but effective.

    On Wednesday, January 6, 2021, 10:20:16 PM CST, Isaac Carter <notifications@github.com> wrote:  
 
 


@burntex is this happening with every video? I'm not seeing any issues, but also running Pix 2.6.3 and Mint 20 64bit.

**Comment by icarter09** [comment]
@burntex no problems and thanks for the update!

**Comment by burntex** [comment]
So basically I needed to install the vdpau pkg which also installed the link nvidia_drv_video.so into /usr/lib/x86_64-linux-gnu/dri . Still it should have more gracefully handled this like gThumb. On the other hand had it not failed so dramatically I still would not have got my system working like it should. For those having video driver issues the following commands can be your friends - vainfo  nvidia-smi inxi -Fxz

on the sync issues using the Intel i965_drv_video.so  playing handbrake QSV  created h.265 files (mkv/m4v) I get the following error if anyone wants to investigate. This only happens with gstreamer apps. No problem using vlc or windows 10 vid players.

0:01:27.810963191  2773 0x7fc48c0175e0 WARN                   vaapi gstvaapidecoder_h265.c:1410:parse_sei: failed to parse SEI messages
0:01:27.810969830  2773 0x7fc48c0175e0 ERROR            vaapidecode gstvaapidecode.c:1180:gst_vaapidecode_parse_frame: parse error 8
0:01:27.811022074  2773 0x7fc48c0175e0 WARN       codecparsers_h265 gsth265parser.c:2300:gst_h265_parser_parse_sei_message: error parsing "Sei message"
0:01:27.811029796  2773 0x7fc48c0175e0 WARN                   vaapi gstvaapidecoder_h265.c:1410:parse_sei: failed to parse SEI messages
0:01:27.811040537  2773 0x7fc48c0175e0 ERROR            vaapidecode gstvaapidecode.c:1180:gst_vaapidecode_parse_frame: parse error 8

Again appreciate the work you guys do .. Pix is pretty much my go to photo/vid tool. If you are looking at adding new features, I really like the sharpen function in VLC Tools/effects and filters/video effects.
