### ISSUE TITLE
Support .heic files (HEIF format or High Efficiency Image File format)

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/pix#134]
Seeing a lot of these from iphones. Be nice if pix natively supported them.

**Comment by leigh123linux** [comment]
Does installing this package help?

https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/heif-gdk-pixbuf_1.6.1-1build1_amd64.deb.html

**Comment by bernd-wechner** [comment]
> gthumb has a commit for this using libheif.
> 
> [GNOME/gthumb@b2d5dff](https://github.com/GNOME/gthumb/commit/b2d5dffc3c22a5fa1253efbceb71000e48c03b9d)

Nice. Not in the current build in the mint repos mind you. And not a pix implementation either ;-). Hoping Pix can introduce this.

**Comment by leigh123linux** [comment]
@bernd-wechner  pix was forked from gthumb https://github.com/linuxmint/pix/commit/783a64bd5ea60fe0717764fd3ecf5fea494b3580

**Comment by bernd-wechner** [comment]
Sure, but pix has a much nice UI. And pix should support .heic files!

**Comment by darkshram** [comment]
Installing the pixbuf-loaders for libheif, avif, and jxl helps solving the issue of viewing this image formats with Pix and Xviewer, but one good reason to back-port not just heif, but also avif and jxl plugins is making Pix stop spaming ~/.xsession_errors with **hundreds/thousands** of lines with `** (gdk-pixbuf-thumbnailer:23224): WARNING **: XX:XX:XX.XX: Could not thumbnail`. Example: I just happen to have several folders with several hundreds for images with some of this formats, so every time I access one of this folders, the **`~/xsession_errors` file grows ridiculously big** and makes it harder to diagnose some other applications.

**Comment by bernd-wechner** [comment]
> Installing the pixbuf-loaders for libheif, avif, and jxl helps solving the issue

Can you provide instructions on how to install pixbuf-loaders for libheif, avif, and jxl and what you mean by "helps". Does it solve the issue or not?

**Comment by darkshram** [comment]
@bernd-wechner:

Fedora and derivatives: `dnf -y install heif-pixbuf-loader`
[Debian](https://packages.debian.org/bookworm/heif-gdk-pixbuf)/[Ubuntu](https://packages.ubuntu.com/impish/heif-gdk-pixbuf) and derivatives: `apt-get install heif-pixbuf-loader`

For other pixbuf-loaders in Fedora and derivatives: `dnf -y install avif-pixbuf-loader jp2-pixbuf-loader jxl-pixbuf-loader webp-pixbuf-loader`
Do not know if they are available in other distros with this same name schema.

**Comment by darkshram** [comment]
@bernd-wechner Installing pixbuf-loaders partially solves this issue because they enable Pix and Xviewer (and other GTK-based image viewer applications) enables support these formats. A native support (as does gThumb) would be better so the user does not have to rely on installing other packages.

Running Pix like this: `pix 2>/dev/null` or creating an alias (`alias pix="/usr/bin/pix 2>/dev/null"`) solves the `~/.xsession_errors` spaming.

**Comment by kmkom** [comment]
I support the proposal to support graphic files in HEIF format (file extension .heif or .heic). A full support in Mint would be very nice!
For Nemo you can install "heif-thumbnailer" to get thumbnails.

"heif-gdk-pixbuf" should bring support for HEIF in pix, but pix then shows me only a small thumbnail, not the actual image.(?)

HEIF is now supported by all operating systems (Android, macOS, iOS, Windows -> see [Wikipedia](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format)). 
One more reason to support the format in Mint out of the box.

**Comment by clefebvre** [comment]
HEIF/AVIF support added in xviewer master and upcoming Mint 21.2.

**Comment by clefebvre** [comment]
Pix rebased on gthumb 3.12, so it now includes support for JXL, HEIF/AVIF.
