### ISSUE TITLE
add keyboard shortcuts for "add to selection"

### ISSUE THREAD

**Issue by deutrino** [linuxmint/pix#15]
It's very inconvenient to have to right-click, delve the context menu, and click again to add to selection. This would be a great way to streamline the process. Preferably with a keyboard shortcut that doesn't twist the fingers... maybe even just the number keys, 1, 2, and 3. Or Alt-1, etc.

**Comment by hoschi-it** [comment]
I'd **love that** feature too! Just googled around to find if there is a shortcut...
Shortcodes are the cause that marking your images while going through them makes it so much more comfortable.

**Comment by vsemecky** [comment]
I'd love that feature too!

**Comment by icarter09** [comment]
@deutrino just test this pix 2.4.8 and the keyboard shortcut for "Add to Selection" is present (`Alt + number key`).
