### ISSUE TITLE
Larger images in HEIF/AVIF/JPEG-XL format are opened with reduced resolution

### ISSUE THREAD

**Issue by sobrus** [linuxmint/pix#157]
```
 * Pix version 2.8.7
 Distribution - Manjaro
```

**Issue**
When opening larger images (for example 26Mpix photos from digital camera) converted to these formats, they are being displayed in significally reduced resolution compared to original JPEG. Reported image resolution is displayed properly, but image itself is downscaled. GIMP is able to open them correctly.

**Steps to reproduce**
1. Convert large image to AVIF/HEIF/JXL format using imagemagick convert command.
2. Try to view it using pix.
3. Compare zoom ratio against original image or zoom in to 1:1 view and compare images.
4. Open file with GIMP or xviewer to view full resolution AVIF/HEIF/JXL image.

**Expected behaviour**
Images are displayed at their full resolution.

**Other information**
This issue also affects gThumb, but xviewer (from x-apps as well) works OK.

**Comment by clefebvre** [comment]
This is fixed on master after the gthumb 3.12 rebase.

![image](https://user-images.githubusercontent.com/1138515/214550571-77dfcf88-cdc9-4ac9-864b-24d4f5a42644.png)
