### ISSUE TITLE
Add ability to go to next/previous image with mouse wheel

### ISSUE THREAD

**Issue by soviet-man** [linuxmint/pix#160]
1. Add ability to go to next/previous image with mouse wheel like in other image viewers.
Now mouse wheel is used for zooming in/out.
Switching to next/previous image is used much more often than zooming. If I want to zoom I can use plus/minus numpads. The more frequent operation is the simplier way must be set to do it.

2. Add ability to skip 5 second forward/backward while viewing video with Right/Left button. 
Now if I press Right/Left button I just go to next/previous file. So inconvenient.

**Comment by clefebvre** [comment]
Following the gthumb rebase (which happened on master this week), the mouse wheel action is now configurable.

**Comment by soviet-man** [comment]
This is good. BUT YOUR MOUSE IS REVERSED!
Now [Ctrl]+[Wheel Down] goes to PREVIOUS image but not to NEXT. It's absurd.

When you use mouse you scroll DOWN to view what is next on the page, and use scroll UP to view previous stuff. Not the opposite.
