### ISSUE TITLE
Deleting Configuration Files

### ISSUE THREAD

**Issue by WhiteDragon84** [linuxmint/pix#164]
```
 * Pix version (pix --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
Pix Version: 2.8.9+elsie
Distribution: Linux Mint Debian Edition 5

**Issue**
Unable to delete configuration files

I have tried: sudo apt purge pix

Have tried deleting:
/home/user/.config/pix
/home/user/.local/share/pix

When I changed configurations the program crashed and won't start again. I'm unable to delete configuration files

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
Please provide a stack trace for the crash.

**Comment by clefebvre** [comment]
I'll close this for now since we're just after completely rebasing pix on the latest gthumb 3.12.
