### ISSUE TITLE
Pix crashes on "Save" of any photos taken with my Casio Exlim, Mint Cinnamon 18.1

### ISSUE THREAD

**Issue by kcaldwel** [linuxmint/pix#17]
I originally discovered the problem using gThumb, which I used with Mint 17. But Pix does the same thing. Both open the photos, I can make changes, but when I try to "Save as", they crash after the JPEG quality selection window pop-up.

It only seems to occur with photos taken with my Casio Exlim camera, which is many of my photos. They all worked fine using gThumb and Mint 17. The photos work fine with Mint 18.1 and Fotoxx. 

The crash occurs even if I have not made any changes to the photos, just try to save them to a different location with the same name. This is an example photo that I am having issues with:
![cimg2341](https://cloud.githubusercontent.com/assets/8403006/23219605/639eb6b4-f8d4-11e6-994b-b75d24723e7f.JPG)

https://www.dropbox.com/s/gp9usqr5699i0io/CIMG2341.JPG?dl=0

 When I start Pix in a terminal:

"(pix:14215): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(pix:14215): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(pix:14215): Gtk-CRITICAL **: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed"

It does start, and will open photos, but crashes on save on my Casio photos.

**Comment by JosephMcc** [comment]
The crash is being caused by a bug in the exiv2 package shipped in Ubuntu Xenial. Relevant bug report can be found here: https://bugs.launchpad.net/ubuntu/+source/exiv2/+bug/1584853
