### ISSUE TITLE
Unwanted white border around image

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/pix#181]
```
 * Pix version (pix --version) 3.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 21.2
```

**Issue**

There is a white border around the image in Pix.

**Steps to reproduce**

Open an image in Pix.

**Expected behaviour**

There is no border.

**Other information**

**Comment by mtwebster** [comment]
workaround: Fullscreen mode removes the border yet the image can still be zoomed in and out.

**Comment by Secret-chest** [comment]
> workaround: Fullscreen mode removes the border yet the image can still be zoomed in and out.

OK, but it is still annoying, earlier versions did not have it

**Comment by collector-ynh** [comment]
Hello, I'd also be very interested in removing this white frame in the new version of PIX. It's really annoying to have this white frame.

I'm currently forced to go back to the previous version to avoid this frame. 

![Sélection_132](https://github.com/linuxmint/pix/assets/101431486/f2e8fcad-19e6-4f41-990e-33f3b22de5e1)

**Comment by Mike6547** [comment]
Hello, I have the same problem. Is there a solution to solve the problem?

**Comment by mtwebster** [comment]
F11

https://github.com/linuxmint/pix/issues/181

**Comment by collector-ynh** [comment]
> F11
> 
> #181

This isn't a solution, though, as we don't intend to view images full-screen every time!

**Comment by keen36** [comment]
Well, mtwebster described it is as a workaround in a previous post, so I assume that much is clear to him...

I do not have any experience with contributing to open source projects and I do not have a lot of experience working with C, but I am a senior backend dev ( mostly PHP, please don't flame me ). I would be willing to look into this, time permitting. Is there a contributor's style guide or something to help me get up and running besides the build instructions in the readme? I do not need anyone to hold my hand but if you guys have some little pointers on where to get started I would love for this to become my entry into open source. If that is a bad idea, just tell me that, too, please ^^

**Comment by mtwebster** [comment]
I wasn't implying 'here's a workaround, deal with it' - I would have closed the issue if I felt that way. It's a way around this until we address it directly.

I've got it more or less done already, just having some internal discussion about it about whether to remove it completely - in the main 'edit' view *and* the thumbnails, or maybe just the edit view. Opinions welcome.

**Comment by keen36** [comment]
Wait sorry, I think I did not express my thoughts clearly enough, I am not a native speaker. I did not think in any way that you meant to imply "deal with it" in your post, rather I interpreted exactly the way you describe: you wanted to provide a workaround until the feature is implemented. I just wanted to calm collector-ynh, who _does_ seem to have misinterpreted your posts.

In any case, great to hear that you already tackled the issue! I do not have an opinion about the thumbnail borders since I do not use that feature.

Thank you for the link, I will look into it. And also thank you for the work you put into this! I hope that part of my donations  to the Linux Mint project finds its way to you somehow ^^

**Comment by mtwebster** [comment]
@keen36 Sorry, that wasn't directed at your post, I was just addressing 'all of the above' - it seemed my suggestion was being misinterpreted. I should have said 'temporary workaround', I suppose.

**Comment by tdlf32** [comment]
When will this problem be fixed?

**Comment by Secret-chest** [comment]
yay

**Comment by collector-ynh** [comment]
PIX still hasn't been updated from the Linux-mint repositories to remove that ugly white frame, what are you waiting for to release the update?

**Comment by Secret-chest** [comment]
> PIX still hasn't been updated from the Linux-mint repositories to remove that ugly white frame, what are you waiting for to release the update?
When a bugfix will be released, this will be released alongside it as it's already fixed upstream.
