### ISSUE TITLE
"1" - for zoom 100% works only on English keyboard layout.

### ISSUE THREAD

**Issue by janos-r** [linuxmint/pix#184]
```
 * Pix version (pix --version)
pix 3.0.2

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Mint 21.2
```

**Issue**
"1" - for zoom 100% works only on English keyboard layout.
Many other layouts have a "+" instead of 1. And unlike other apps that associate numbers with shortcuts, here it is not possible to:
A) Trigger the event with a keyboard combination that writes the number "1" like shift+<key1>
B) Pressing 1 on the numPad

**Steps to reproduce**
Zoom into any image.
Either
A) Press 1 on numPad
or
B) Press 1 or shift+1 (under F1) on a Czech keyboard, or any that doesn't have the numbers primary under the F row.

**Expected behaviour**
That at least the 1 on numPad would work.
Or that also the previous / or *  would trigger it.
Or that the shortcuts could be edited.

**Other information**

**Comment by mtwebster** [comment]
You can edit shortcuts in preferences, can't you?
![image](https://github.com/linuxmint/pix/assets/262776/edf43530-cf5e-45df-b5c7-ca064b8c0221)

**Comment by janos-r** [comment]
I am so so sorry for not noticing this before!
Thank you, closing the ticket.
