### ISSUE TITLE
Application crash when opening jpg file

### ISSUE THREAD

**Issue by jcdegiorgi** [linuxmint/pix#19]
Hi all,

FYI,
I try to open a jpg file (jpeg format) and Pix is crashing. Here are some details:
$ pix test.jpg 

(pix:4156): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
pix: ../../../../src/cairo-xlib-surface-shm.c:619: _cairo_xlib_shm_pool_create: Assertion `*ptr != ((void *)0)' failed.
Aborted

Note:
I strongly think this is a problem with the picture (it's actually a scan of a real picture) because I get a similar crash with xviewer.
But it can be opened with Gimp and ImageMagic.

Thanks guys.

Jean-Claude

**Comment by icarter09** [comment]
@jcdegiorgi are you still experiencing this issue?

**Comment by jcdegiorgi** [comment]
@icarter09 
Yes, it still does crash.

Here are some more infos:
**Pix version:** 
pix 1.0.6, Copyright © 2001-2010 Free Software Foundation, Inc.

I noticed that pix is crashing only with panoramic pictures. Here is an example:
**JPG file size:** 
21M

**JPG file info:**
20160804_115645.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=12, height=19648, manufacturer=samsung, model=SM-G850F, orientation=upper-right, xresolution=210, yresolution=218, resolutionunit=2, software=G850FXXU2COI3, datetime=2016:08:04 11:56:45, width=3008], baseline, precision 8, 3008x19648, frames 3
This picture is a panoramic one.

**Error after crash:**
$ pix 20160804_115645.jpg
(pix:4598): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
pix: ../../../../src/cairo-xlib-surface-shm.c:619: _cairo_xlib_shm_pool_create: Assertion `*ptr != ((void *)0)' failed.
Aborted

Launching pix without arguments gives me this message:
$ pix
(pix:5765): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
Error: Upper boundary of data for directory Photo, entry 0x0000 is out of bounds: Offset = 0x00000001, size = 303109, exceeds buffer size by 302383 Bytes; truncating the entry

I tried to install newer versions but I keep having problems:
**pix-2.2.1**
$ ./autogen.sh 
*** WARNING: I am going to run 'configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** './autogen.sh' command line.
./autogen.sh: 27: ./autogen.sh: glib-gettextize: not found
_Sorry, can't find this package on my distrib (linux-mint 18 Sarah)_

**pix-2.0.1**
$ autoconf 
configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:42: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:101: error: possibly undefined macro: AC_DEFINE
configure.ac:125: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:256: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
$ ./configure 
./configure: line 2176: syntax error near unexpected token `1.11'
./configure: line 2176: `AM_INIT_AUTOMAKE(1.11 foreign no-dist-gzip dist-xz 

**pix-1.4.1**
$ autoconf 
configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:42: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:101: error: possibly undefined macro: AC_DEFINE
configure.ac:125: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:256: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT

Yours sincerely,
Jean-Claude

**Comment by leigh123linux** [comment]
Sorry pix-1.0.6 is EOL and wont be fixed.
