### ISSUE TITLE
Request: slideshow options

### ISSUE THREAD

**Issue by GregoriMarow** [linuxmint/pix#20]
Hi,
I want to request options for the slideshow.

Compare with options for "Irfan View":
https://irfanview-forum.de/attachment.php?s=021e4f9f747af12792d14057098d205e&attachmentid=2112&d=1266523681

**Comment by gordon-morehouse** [comment]
This should be broken down into separate individual feature requests. See also #26

**Comment by JosephMcc** [comment]
@gordon-morehouse is right. I would also prefer the reason why a feature would be useful or a good idea, not just "I want all of this".
