### ISSUE TITLE
Video plays in a separate window

### ISSUE THREAD

**Issue by yumpyy** [linuxmint/pix#203]
### Distribution

Arch Linux

### Package version

3.2.2

### Frequency

Always

### Bug description

Video in pix starts outside of the main window instead of being embedded but the controls of the player stays in the main window. Here is a video : 
[Video](https://rimgo.projectsegfau.lt/a/zECQicC)

And a log file when pix is launched through terminal
[Log](https://termbin.com/19hk)

### Steps to reproduce

1. Open pix
2. Play a video

### Expected behavior

I think the video is supposed to be embedded inside the main window instead of playing as a pop-up

**Comment by haspper** [comment]
Installing gThumb along with PIX solved the issue. I double checked but I wasn't missing any dependencies even the optional ones. 
Maybe it was a issue related to installing PIX from AUR.

**Comment by yumpyy** [comment]
Okay so, Getting pix from AUR doesn't install `gst-plugin-gtk` which then leads to this issue.
