### ISSUE TITLE
Debian 12.5 stable does not meet dependencies

### ISSUE THREAD

**Issue by tbone2k-git** [linuxmint/pix#209]
### Distribution

Debian 12.5

### Package version

pix 3.2.2 (just downloaded the archive, did not run)

### Frequency

Always

### Bug description

When trying to install pix on most recent Debian stable (12.5) it seems there are more recent versions of various packages required. I come across this quite often when "side loading" applications and I actually wonder why that is, is all the world running bleeding edge / unstable rolling releases, but me? I'm not sure! o)

Anyway, this is the message I get after trying the last step of the theoretical installation (see "Steps to reproduce" for all the 3 commands I ran).

> sudo dpkg -i pix_3.2.2_amd64.deb 
Selecting previously unselected package pix.
(Reading database ... 118946 files and directories currently installed.)
Preparing to unpack pix_3.2.2_amd64.deb ...
Unpacking pix (3.2.2) ...
dpkg: dependency problems prevent configuration of pix:
 pix depends on libxapp1 (>= 2.6.0); however:
  Version of libxapp1:amd64 on system is 2.4.2-3.
 pix depends on xapps-common (>= 2.5.0); however:
  Version of xapps-common on system is 2.4.2-3.

> dpkg: error processing package pix (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for man-db (2.11.2-2) ...
Errors were encountered while processing:
 pix

### Steps to reproduce

Run these commands:
sudo apt install libbrasero-media3-1 libclutter-1.0-0 libclutter-gtk-1.0-0 libwebkit2gtk-4.0-37 libxapp1 dcraw xapps-common
sudo dpkg -i pix-data_3.2.2_all.deb
sudo dpkg -i pix_3.2.2_amd64.deb

### Expected behavior

Run on most recent stable release of Debian, do not depend on packages and versions not available (yet).

**Comment by leigh123linux** [comment]
Either use LMDE or file the issue against the debian xapp bug tracker.

**Comment by tbone2k-git** [comment]
Hello leigh123linux! o)

You mean I shall reinstall the OS to make use of this image viewer? Mhh, that's not an option I guess. Do you know, what is it you need in the more recent xapp package? Is it a feature or bug fix or just so other distributions cannot make use of this application? o) This is a real question, I'd like to know! o) 

I had a similar thing with an emulator these days, it was compiled against a brand new CLIB version, no way to run it if you don't use a rolling / testing release. But they fixed it, they just set compile target 2-3 versions lower, so more people can make use of the provided binaries. I kind of liked that and I guess the developers did as well, since more people can enjoy their work! o)

I'm quite new to the Linux world and some things don't make sense to me yet.

If I think back to the Windows days, I hardly remember any program requiring me to update system specific files on my computer, which are barely 9 months old to something more recent, which is not yet even released for my OS, to make the program work. But hey.. what do I know.. o)

Thank you! o)
