### ISSUE TITLE
arrows should navigate in full size view

### ISSUE THREAD

**Issue by deutrino** [linuxmint/pix#21]
In full size view (what the user sees after double-clicking a thumbnail), the right arrow key should advance to the next photo (in addition to any other keys which may do so) and the left arrow key should move to the previously viewed photo. Currently there is no obvious way to move backward through the photos other than to return to thumbnail view and use the mouse.

**Comment by chuinul** [comment]
Are you sure of this? Using Pix 1.4.5 on LM18.2 (Cinnamon), left/right arrows do move to the next/previous picture.

**Comment by deutrino** [comment]
This is working for me in the latest version of Pix.
