### ISSUE TITLE
libjxl_threads.so.0.9

### ISSUE THREAD

**Issue by Sidethorn** [linuxmint/pix#210]
### Distribution

Arch

### Package version

pix 3.2.2

### Frequency

Always

### Bug description

Not  launching on Arch because ask for libjxl_threads.so.0.9 when library has moved to 0.10 

### Steps to reproduce

Launching Pix

### Expected behavior

working

**Comment by Sidethorn** [comment]
As it says not launching on arch because it asks for outdated libjxl

**Comment by leigh123linux** [comment]
You need to file the issue at archlinux as their package needs to be rebuilt by them!
