### ISSUE TITLE
RAW file viewing

### ISSUE THREAD

**Issue by BMWDriver** [linuxmint/pix#24]
Hi,
I've installed dcraw in order to be able to view my Sony ARW files with Pix, but no dice. They are 25 MB each, and I can import into Gimp using the dcraw gimp plugin no problem. Perhaps I need to do something extra? Tried the Linuxmint forum, but to no avail.

Thanks!

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/pix/issues/13
