### ISSUE TITLE
duplication of effort with xviewer

### ISSUE THREAD

**Issue by deutrino** [linuxmint/pix#27]
Both xviewer and Pix are part of the Linux Mint project. It would be good to officially define the scope of xviewer vs Pix to avoid duplication of effort.

For example, there is already a slideshow feature in both. Why?

I find myself tempted to submit a pet feature request regarding the slideshow to both projects in case it gets done in one and not in the other. Even without having such an intent, over time users are going to submit duplicate feature requests, and developers may spend time writing duplicate features.

I suggest the following:

xviewer should be kept as simple as possible
extended features (slideshows, tagging, whatever) be kept in Pix
basic, commonly used features (crop, rotate, export as) be common to both for convenience, *after* it has been carefully thought through

See also linuxmint/xviewer#33

**Comment by icarter09** [comment]
The Mint team already keeps most of this in mind when going over tickets and reviewing PRs. You are correct to say that xviewer is being kept as simple as possible while Pix contains more extended functionality.
