### ISSUE TITLE
Add Ctrl+w to close current window

### ISSUE THREAD

**Issue by ambs** [linuxmint/pix#30]
```
 * Pix version (pix --version) - 1.4.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
```

**Issue**

I can't guarantee, but I think older versions had Ctrl+w to close the current window.
Nevertheless, it would be so useful.

Thanks

**Comment by versus666** [comment]
I confirm, older versions obey Ctrl+W, the current doesn't.
I think it's annoying too.
The scroll wheel changes too, at least make it a choice in prefs.

**Comment by ambs** [comment]
Well, this should be an easy fix, right?

**Comment by ambs** [comment]
Was trying to find the proper place to define the shortcut, for #hacktoberfest, but complete lost on this code.

**Comment by clefebvre** [comment]
This is fixed.
