### ISSUE TITLE
Could not show link - Too many open files

### ISSUE THREAD

**Issue by starkgate** [linuxmint/pix#35]
```
 * Pix 1.4.5
 * Mint 18.2 Xfce
```

**Issue**

The following popup appears when I try to click on the Website link, in the About menu.
![screenshot_2017-07-19_09-09-50](https://user-images.githubusercontent.com/12874678/28355099-e5b7d782-6c62-11e7-96b4-cae6a11a0447.png)

**Steps to reproduce**

Click on the Website link, in the About menu.

**Expected behaviour**

The link should open the page in the browser. There's no reason having too many files open should prevent that.

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
Pix v2.2.1

Unable to reproduce this issue. Link opens as expected.
