### ISSUE TITLE
Status bar is not themed with dark colors

### ISSUE THREAD

**Issue by Deevad** [linuxmint/pix#36]
```
 * Pix version 1.4.5
 * Distribution - Mint 18.2 Cinnamon 64bit
```

**Issue**

Hi, the status bar is not themed with dark colors. Pix doesn't look as good as it can potentially be.

**Steps to reproduce**

My selected theme is Mint-Y. Open a picture with Pix. If you don't have the status bar visible , activate it with View > Status bar  (useful to get image geometry, size, date, etc...) . It will look like that:

![2017-07-24_screenshot_121240_net](https://user-images.githubusercontent.com/4021867/28519023-5779210e-706a-11e7-9897-3736fc17dffc.jpg)

**Expected behaviour**

I would like the grey status bar to be dark as does Xviewer for its status bar in this screenshot:

![2017-07-24_screenshot_121323_net](https://user-images.githubusercontent.com/4021867/28519046-6fb3ee2a-706a-11e7-82d9-5feac5965898.jpg)

**Comment by JosephMcc** [comment]
I can't seem to reproduce this problem.
