### ISSUE TITLE
Paste Image shortcut key conflicts with Print shortcut

### ISSUE THREAD

**Issue by s101d1** [linuxmint/pix#39]
```
 * Pix version 1.2.1
 * Distribution - Linux Mint 18.1
```

**Issue**
Paste Image shortcut key is same as Print shortcut (Ctrl + P)

**Description**
Just check menu Edit -> Paste Image, you would see the shortcut key is Ctrl + P, same as Print shortcut.

I think Paste Image shortcut key should be Ctrl + V just like other image editors.

**Comment by icarter09** [comment]
Linux Mint 19.2
Pix v2.2.1

Paste Image is no longer mapped to `Ctrl + P`
