### ISSUE TITLE
Cannot open a JPG file without extension

### ISSUE THREAD

**Issue by PeterCantropussy** [linuxmint/pix#40]
```
 * Pix version (pix --version)
Pix 1.4.5

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18.2 Sonya 64-bit

**Issue**
Cannot open a JPG file without extension. Pix try to open it but only displays a blinking thumbnail of the jpg file


**Steps to reproduce**
Open a JPG file without extension


**Expected behaviour**
Open the file and/or warn the user that file has no extension


**Other information**
Linux 4.10.0-35-generic x86_64

**Comment by chuinul** [comment]
I encounter the same issue. Expected behaviour is probably what Xviewer does: open the file.

**Comment by gm10** [comment]
Still happening with Pix 2.0.3 / LM 19.1. Also affects other image file types - probably all of them as long as there's no extension. You need to pass the image file as an argument, I cannot reproduce it when opening the same file from within Pix.

**Comment by icarter09** [comment]
Linux Mint 19.2
Pix v2.2.1

Verified this is still an issue. Reproduced with both `png` and `jgp` file where neither contained the extension.

**Comment by icarter09** [comment]
Linux Mint 19.3
Pix 2.4.3

Still an issue.

**Comment by DoodlesEpic** [comment]
Linux Mint 20.1
Pix 2.6.3

Still an issue, PNG images flicker if you add them to pix without the file extension.

**Comment by Julvenzor** [comment]
This error is still present on Mint 20.3. I don't know if it happens on Mint 21. It occurs with all images if they lack specified extension in their file name.

Cheers!

**Comment by mtwebster** [comment]
Flickering fixed:
https://github.com/linuxmint/pix/commit/a9a46ce4266fb82b9e6ef0db5dc65aac99e4ce50

To detect images with incorrect extensions you need to go into Preferences->Browser and check "Determine image type from content".

**Comment by mtwebster** [comment]
Fast content detection is now disabled by default:

https://github.com/linuxmint/pix/commit/93ca9b62a6323e17da5463432028cbb105fd2b5f
