### ISSUE TITLE
Swapped icons

### ISSUE THREAD

**Issue by PeterCantropussy** [linuxmint/pix#41]
```
* Pix version (pix --version)
Pix 1.4.5

* Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18.2 Sonya 64-bit
Linux 4.10.0-35-generic x86_64
```

**Issue**
Icons for "edit file" and "file properties/histogram" are swapped

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
No. The icon used for properties is "document-properties-symbolic" which is a standard icon used for that across many apps.
