### ISSUE TITLE
2 Untranslatable Korean items in launchpad 

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/pix#5]
There are 2 untranslatable lines for Korean even in English, 
https://translations.launchpad.net/linuxmint/latest/+pots/pix/ko/+translate?show=untranslated
Korean Translation don't use plural.

* Error in Translation: 		
'msgstr[0]' is not a valid C format string, unlike 'msgid_plural'. Reason: In the directive number 1, the character '&' is not a valid conversion specifier. 

* Number 1106 & plural

Are you sure you want to move to trash the %&#x27;d selected file?
선택하신 파일 %&#x27;d를 휴지통으로 보내시겠습니까?

and it doesn't commit even without that "%&#x27;d" translation
선택하신 파일을 휴지통으로 보내시겠습니까?

* Number 1107 & plural

Are you sure you want to permanently delete the %&#x27;d selected file?
선택하신 파일 %&#x27;d를 완전히 지우시겠습니까?

and it doesn't commit even without that "%&#x27;d" translation
선택하신 파일을 완전히 지우시겠습니까?

**Comment by clefebvre** [comment]
Hi,

I copy/pasted your text in there and it works for me.

LP is funny sometimes... in any case, it's in now :)
