### ISSUE TITLE
EXIF display issue

### ISSUE THREAD

**Issue by garypark18** [linuxmint/pix#51]
```
 * Pix version 1.6.2
 * Distribution - Mint 18.3 'Sylvia'
```

Display of EXIF data in properties window shows HierarchicalSubject value without commas. Perhaps this item should have been name HierarchialSubjects or HierarchicalSubjectList because it is a comma separated list. That syntactic data is lost if the commas are deleted.

**Steps to reproduce**
Open the attached file

**Expected behaviour**
The commas should be displayed.

**Other information**
I am unsure if the problem originates in this program or in some library that it calls but this is where I see the problem
![dsc_0069](https://user-images.githubusercontent.com/19440146/40589176-bd2456a2-619d-11e8-885a-e12601aa19f8.jpg)

**Comment by icarter09** [comment]
@garypark18 are you still experiencing this issue?
