### ISSUE TITLE
Crop does not work and then Pix freezes or crashes

### ISSUE THREAD

**Issue by Napaja** [linuxmint/pix#58]
```
 * Pix version: 1.8.2
 * Distribution: Mint  19.0 / Cinnamon
```

**Issue: Suddenly, from today (Dec.12, 2018) Pix went wrong, eg.: Crop does not work and then Pix freezes or crashes.
The last system updates are captured on the attached screeshot. 
![last system updates](https://user-images.githubusercontent.com/22030217/49901836-8c5dae80-fe62-11e8-907c-92295c9c757e.png)
**

**Steps: I am launching PIX and initiate a crop action**

**Expected behaviour: until yesterday I could resize the area and crop it.**

**Other information: PIX is a very useful app for the most common photo editings, which I was using it very often without any problem. Now I un- and re-installed it but it still does not work.**

**Comment by icarter09** [comment]
@Napaja are you still experiencing this issue?

**Comment by Napaja** [comment]
No, it works again fine.   
Many thanks!

**Comment by icarter09** [comment]
@Napaja thanks for the update.
