### ISSUE TITLE
Thumbnail pane shows place holder icons after program start if pane is located horizontally

### ISSUE THREAD

**Issue by bohlstry** [linuxmint/pix#59]
```
 * Pix version: 2.0.3 (from AUR)
 * Distribution: Arch with Cinnamon desktop
```

**Issue**

Switching from browser to viewer the first time after program start shows only thumbnail "place holder" icons if thumbnail pane is located **horizontally**. A vertically placed thumbnail pane shows valid pictures immediately.

**Update 2019-01-08:**
Tried every old version, starting from V1.6.2. This bug was introduced by commit a24857f (Fix Gtk3.20+ issues), all previous versions are working as expected!

**Steps to reproduce**

Go to preferences, set "Thumbnails in viewer" to "on the bottom". Activate viewer mode and make thumbnail pane visible (F8). Restart Pix and activate viewer mode. Thumbnail pane is visible, but doesn't show any real pictures (see attachment). Hiding (F8) and viewing the thumbnail pane again (F8) is a workaround to refresh!

**Expected behaviour**

Pix should show valid thumbnails immediately!

**Other information**

![screenshot from 2019-01-06 21-15-21](https://user-images.githubusercontent.com/46426739/50741359-8b6b3300-11fc-11e9-8c97-522b675f6267.png)

**Comment by icarter09** [comment]
@bohlstry are you still experiencing this issue?
