### ISSUE TITLE
Selected text in "Import from Folder" dialog is unreadable (white over white background) 

### ISSUE THREAD

**Issue by xndrme** [linuxmint/pix#6]
I'm using Pix to organize my pictures, I use it a lot to import all the pictures from my devices. I've notice that in the last version (1.0.5) the import dialog (File>Import From>Folder...) has an annoying issue: when an item is selected the text turns white over white background, effectively making it unreadable.
I'm using Linux Mint 18 Cinnamon 64-bit, Mint-X-Blue theme for the controls.
Here an image of the dialog without selected items:
![screenshot from 2016-07-11 09-00-19](https://cloud.githubusercontent.com/assets/4387571/16722382/76abacc0-4746-11e6-966e-c7508b34df52.png)
And here what happens when you select an item (notice there is no text):
![screenshot from 2016-07-11 09-00-43](https://cloud.githubusercontent.com/assets/4387571/16722393/897fcb74-4746-11e6-969d-bea29bfb2cb4.png)

**Comment by JosephMcc** [comment]
Just did a bit of testing. This looks to be an issue specific to the the Mint-X theme not pix itself.

**Comment by xndrme** [comment]
Ah! OK, should I close it? Where should I post it?

**Comment by JosephMcc** [comment]
Best would be to close this issue and open one here: https://github.com/linuxmint/mint-themes-gtk3 instead. That way I won't forget I need to fix it :)

**Comment by xndrme** [comment]
Ok, done.
