### ISSUE TITLE
Image rotation not respected in .mov files

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/pix#61]
```
 * Pix version 1.8.2
 * Distribution - Mint 19
```

**Issue**
Browser respects video rotation and reports it right, view does not respect it.

**Steps to reproduce**
1. Browse a folder with pix that contains a .MOV file from an iPhone that reports in Properties: image-orientation: rotate-90.
2. See how the thumbnail is right way up?
3. Double-click the thumbnail - the viewer opens
4. Observe that it plays sideways ... (the rotation not respected).
5. Press CTRL+I, and check the properties and confirm again that **image-orientation: rotate-90** is reported

**Expected behaviour**
That the video plays the right way up.

**Other information**
Seems a glaringly obvious problem. I reported same for Linux Mint's supplied tool Xplayer a few years ago now I think, and they fixed it. Funny to find it in Pix now.

**Comment by icarter09** [comment]
@bernd-wechner are you still experiencing this issue?

**Comment by bernd-wechner** [comment]
Just checked Pix 2.2.1 and yes problem still exists. I don't have many .MOV files, they tend to come off a family member's iPhone. But Xplayer respects the embedded rotation and pix 2.2.1 does not.

**Comment by icarter09** [comment]
@bernd-wechner thanks for the update.

**Comment by icarter09** [comment]
Pix v.2.4.8
Mint 20

@bernd-wechner can you post a .mov file that is displaying the issue? I just tried out a couple of sample .mov files and I'm not seeing any issue. The thumbnail orientation looks correct and the files do not play sideways. Thanks.

**Comment by bernd-wechner** [comment]
Here's one example I just dug up:

https://mega.nz/file/lHJlBQZT#kkKJZTNkthWkxJdMTbE4b2NXrx52s7k2DJaDUiw-Duw

Am using Mint 20 and Pix 2.4.11. The default video viewer in Mint 20 displays it with proper rotation. Pix not.

**Comment by icarter09** [comment]
@bernd-wechner much appreciated sir!  Yes that .MOV file does show the issue.

**Comment by leigh123linux** [comment]
@icarter09  The issue is also present in gthumb-3.10.0

**Comment by clefebvre** [comment]
Still present in gthumb 3.12.0.

**Comment by klemens** [comment]
I have a potential fix in #195, it would be nice if any of you could test if it works with your files (I already tested https://github.com/linuxmint/pix/issues/61#issuecomment-667632822 and it is displayed correctly now) and potentially older gstreamer versions (I only tested with the latest 1.22.6 on arch).
