### ISSUE TITLE
can't change default sort order

### ISSUE THREAD

**Issue by brainchild0** [linuxmint/pix#62]
```
 * Pix version 2.03
 * Distribution - Mint 19.1
```

**Issue**

Unable to change default sort order.

**Steps to reproduce**

Change sort order to _by name_ for current folder.  Enter new folder not previously visited.  Sort order is restored to _by modification date_.

**Expected behaviour**

Default sort order can be changed, affecting all yet unvisited folders.  

Also, sort order of current folder can be changed easily, such as by toolbar icons, without navigating through menus or invoking dialog boxes.

**Comment by icarter09** [comment]
Pix v2.4.8
Mint 20

I'm not able to reproduce this bug. The sort order is still set to `file name` when I go into a folder not previously visited.

@brainchild0 can you retest this issue once you upgrade Pix? Thanks.
