### ISSUE TITLE
Meta data addition corrupts exif data

### ISSUE THREAD

**Issue by mgray06** [linuxmint/pix#72]
```
 * Pix version 2.0.3+tessa
 * Distribution - Mint 19.1
```

**Issue**
Adding an image description also adds this text as user comment but incorrectly.
When the description field in Pix is saved this is how exiftool responds
exiftool -imagedescription testshota.JPG 
Warning: Invalid EXIF text encoding for UserComment - testshota.JPG

**Steps to reproduce**
Add some description metadata to any jpeg
issue the command exiftool -imagedescription testshota.JPG 

**Expected behaviour**
The description entered will be output

**Other information**
I think usercomment needs a character code

exiftool sometimes ignores this incorrect exif update
exiftool -idescription testshota.JPG
will provide the description
BUT the -description tag doe not work as a print format

**Comment by icarter09** [comment]
@mgray06 are you still experiencing this issue?
