### ISSUE TITLE
Picture greyed out even if not selected

### ISSUE THREAD

**Issue by alexanderdd** [linuxmint/pix#73]
```
 * Pix version 2.0.3
 * Distribution - Linux Mint 19.1 Cinnamon
```

**Steps to reproduce**
1. select a picture in browser view, the picture has lower saturation and a green boarder
1. click somewhere else in browser view to de-select it
1. the picture has no green boarder anymore but is still greyed out (has lower saturation)
(when I try to make a screenshot it changes to full saturation!!)

**Expected behaviour**
upon deselecting, every picture should have full saturation

**Other information**

**Comment by N30-X13** [comment]
Very nice, Thank you for your insight.... 
                              Grateful General Garbage

**Comment by icarter09** [comment]
Linux Mint 19.3
Pix 2.4.3

Was able to reproduce this issue.
