### ISSUE TITLE
Imperial to Metric is not correct

### ISSUE THREAD

**Issue by TorfDrottel** [linuxmint/pix#78]
```
 * Pix version 2.0.3
 * Distribution - (Mint 19.1)
```

**Issue**
The Printing Dialog uses cm instead of mm, when changing from inch to mm.
1 inch is translated to 3mm - but 1 inch is 2.54cm or 25.4mm. 
This would be only a naming issue if 2.5 cm could be set, but only integers are accepted in mm mode

**Steps to reproduce**
select a picture, activate printing command to open printing dialog. the measurement can be set on the third tab

**Expected behaviour**
1 inch should be 25mm, 10 in should be 25.4mm and so forth

**Other information**
when measuring is set to pixels, I see the same values as "mm", which means that 1 pixel would measure 3cm. I'm pretty sure the image has a higher dpi value than 1. This seems to be the same or an related bug...

**Comment by mtwebster** [comment]
https://github.com/linuxmint/pix/commit/1d7bce791848aba5d1849cbecf1ae25a9a862164

https://github.com/linuxmint/pix/commit/4e034584be3fbf9bb168f2810ae740635845bf84
