### ISSUE TITLE
Undocumented mouse behaviour in slideshow mode

### ISSUE THREAD

**Issue by pkail** [linuxmint/pix#82]
```
 * Pix version (pix --version)
2.0.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1 64-bit
```

**Issue**
The documented behaviour of the mouse doesn't work:

"Moving the mouse will activate a popup control panel briefly. This can be used to navigate to the next or previous image, or change zoom levels."

Interestingly enough, though, undocumented behaviour does (right and left mouse clicks move the image forwards and back).

**Steps to reproduce**
Click mouse

**Expected behaviour**
See above.

**Other information**

**Comment by icarter09** [comment]
@pkail where is the documented behaviour located? Thanks.
