### ISSUE TITLE
No ability to remove images from selectionspi 1/2/3

### ISSUE THREAD

**Issue by zhum** [linuxmint/pix#84]
```
 * Pix version 2.0.3,
 * Distribution - Mint 19.1
```

**Issue**
Images can be added to 'Selection 1', but cannot be removed from it

**Steps to reproduce**
Select any image, click right mouse button on it, choose 'Add to selection/Selection 1'.
Optionally go to 'Bookmarks/Selections/Selection 1', you can see selected image, but it is not possible to remove it from 'Selection 1'.

**Expected behaviour**
There should be reasonable and convenient way to remove one/all images from selections 1/2/3.

**Comment by guyhillyer** [comment]
Is there any way, reasonable and convenient or not, to clear a selection?  I can't find it anywhere.

**Comment by icarter09** [comment]
Using `Alt+Shift+(selection number)` will remove the image from the given selection group. I'll look into making this more intuitive.
