### ISSUE TITLE
Pix crashes on thumbnail creation whene there is a GIMP 2.10.x file present

### ISSUE THREAD

**Issue by gimplyworxs** [linuxmint/pix#89]
```
 * Pix version pix 2.4.5
 * Distribution - (Mint 19.2 MATE)
```

**Issue**
Pix crashes on thumbnail creation when there is a GIMP 2.10.x file present

**Steps to reproduce**
I've uploaded a folder with pics here: 
https://my.pcloud.com/publink/show?code=kZUvCfkZsjtNpkNS6fjNXrPPnKuMm5uQpXUy

Decompress the pictures to a folder. Go into that folder. Right-click on a .png file to open it with pix.
As soon as it comes to creating thumbnails of a xcf file pix closes/ crashes.
Stack trace is attached in my upload as well.

**Expected behaviour**

**Other information**

**Comment by mtwebster** [comment]
I'm not sure why the xcf files you supplied aren't getting thumbnailed.  If I save one of your jpg's as an xcf, it thumbnails it just fine.

**Comment by gimplyworxs** [comment]
Pix cannot make thumbnails of GIMP 2.**10**.x files. Maybe it's only the problem when the GIMP file is very big, or has many layers ... I don't know. But I have quite a heap of those crash reports ... so there is a problem somewhere. 
Anyway, thanks for looking into it.

**Comment by mtwebster** [comment]
Ah ok.  I tested with gthumb also, and I got the same behavior.  It won't crash anymore at least (pending a new release)

**Comment by gimplyworxs** [comment]
gthumb is ok for me, too. It never had those problems.
