### ISSUE TITLE
Question: New catalog - diff bet "tag" and "embedded tag"?

### ISSUE THREAD

**Issue by elihubogan** [linuxmint/pix#9]
Hi there, saw this in my new Mint install, thrilled to use it to handle a 30k image library that needs tagging. 

First question that came up with catalog creation was whether to use 'tags' or 'embedded tags' which brought me up short. I don't want to go too far down the wrong path, so if there's anything I'm missing in the help docs I apologize!

**Comment by icarter09** [comment]
@elihubogan were you able to figure out which tag to use?

**Comment by elihubogan** [comment]
@icarter09 No I never did - I'd forgotten about this entirely, but time to rediscover! :)
