### ISSUE TITLE
Debian Testing / Bullseye Alpha 1 missing libexiv2-14 from repository

### ISSUE THREAD

**Issue by jeffmcneill** [linuxmint/pix#94]
I'm installing Pix on Bullseye Alpha 1 (Debian 11 / testing). I'm using the latest unstable release for LMDE3. This works well on Debian 9 and Debian 10. However on Debian Testing It complains that libexiv2-14 needs a version of .25 or greater. This file is not available in the bullseye repositories. Instead I had to get it from:

https://debian.pkgs.org/10/debian-main-amd64/libexiv2-14_0.25-4_amd64.deb.html

Just an FYI when it comes to Debian Testing / Bullseye.

**Comment by leigh123linux** [comment]
Try LMDE4 pix

http://packages.linuxmint.com/list.php?release=Debbie

If that fails DIY as it isn't our issue.

**Comment by jeffmcneill** [comment]
Note: this is still an issue with Debian Testing (Alpha 3 of Bullseye, 2020-12). That is, the libexiv2-14 is not included in the latest LMDE4 master for Pix (2021-01-03). I had to get this file from a Kali Linux repository: http://kalirepo.pxinfra.net/kali-rolling/pool/main/e/exiv2/libexiv2-14_0.25-4_amd64.deb

The point I am making is that you've got a missing dependency in the application itself, regardless of where the dependency might also be loaded elsewhere in the LMDE system.
