### ISSUE TITLE
Pix hangs when opening a folder with image files containing Tags

### ISSUE THREAD

**Issue by woutable** [linuxmint/pix#96]
```
 * Pix version 2.4.6
 * Distribution - Linux Mint 19.3 Cinnamon
```

Pix uses 100% CPU when the folder contains an image with tags saved in the file itself.

As soon as you add tags to a picture file in Pix, it starts to use 100% of the CPU.
Identical behaviour when image files in the opened folder contain tags added with other programs like digiKam.

**Comment by iaurkano** [comment]
Hi,
i have a similary PIX behaviour on my system.
When i launched PIX, it hangs. 

Pix does not consumme 100% of CPU ressources but, 10-20% of each core, and my HDD (SSD) is always on.

i tried to launch pix from the command line and i found these error : 

`Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory (Last IFD item) with 19712 entries considered invalid; not read.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory (Last IFD item) with 19712 entries considered invalid; not read.
Error: Directory (Last IFD item) with 19712 entries considered invalid; not read.
Error: Directory (Last IFD item) with 19712 entries considered invalid; not read.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory (Last IFD item) with 19712 entries considered invalid; not read.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.`

it seems this error is coming from image Exif TAG !!
Regards.

**Comment by iaurkano** [comment]
Further investigations later,

Gthumb 3.6.1 does not have this issue, even if i get the same, but not really identical, messages from the command line i mean : 

```
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory Image: Next pointer is out of bounds; ignored.
Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
Error: Offset of directory Image, entry 0x0102 is out of bounds: Offset = 0x00000000; truncating the entry
Error: Offset of directory Photo, entry 0x011a is out of bounds: Offset = 0x00000000; truncating the entry
Error: Offset of directory Photo, entry 0x011b is out of bounds: Offset = 0x00000000; truncating the entry
Error: Offset of directory Photo, entry 0x0132 is out of bounds: Offset = 0x00000000; truncating the entry
```

i will use Gthumb.

Thank's for all.

**Comment by icarter09** [comment]
What are the steps to reproduce this issue? When I add a tag to an image in Pix, I see no spike in the CPU or Pix hanging.
