### ISSUE TITLE
file associations

### ISSUE THREAD

**Issue by STEPHEN-GOLDBOROUGH** [linuxmint/pix#99]
```
 * Pix version (2.4.6)
 * Distribution - (Mint 19.3 Xfce)
```

**Issue**

no pix related entries in /home/USER/.local/share/applications/defaults.list; plenty of GIMP entries even though GIMP's not included in a standard LM 19 install

**Steps to reproduce**

check system and local default iists

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
What files or file types are you wanting pix to associate with the defaults.list?
